baseURL = "https://ukrainians.org.au/"
languageCode = "en-au"
title = "AFUO - СУОА"
theme = "hyde"

[Menus]
  main = [
      {Name = "Ласкаво просимо до Австралії", URL = "/welcome-to-australia/"},
      {Name = "About", URL = "/about/"},
      {Name = "Contact us", URL = "/contact-us/"},
      {Name = "Organisations", URL = "/about/member-organisations/"},
      {Name = "Blog", URL = "/"},
  ]

[Params]
  description = "The Australian Federation of Ukrainian Organisations – Союз Українських Організацій Австралії"
  copyright = "Copyright"
