baseURL = "https://ozeukes.com/"
languageCode = "en-us"
title = "AFUO - СУОА"
theme = "hyde"

[Menus]
  main = [
      {Name = "Ласкаво просимо до Австралії", URL = "/newcomers/"},
      {Name = "About", URL = "/about/"},
      {Name = "Contact us", URL = "/contact-us/"},
      {Name = "Partners", URL = "/partners/"},
  ]

[Params]
  description = "The Australian Federation of Ukrainian Organisations – Союз Українських Організацій Австралії"
  copyright = "Copyright"
